// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/rock-paper-scissors.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandShape int32

const (
	HandShape_HAND_SHAPES_UNKNOWN HandShape = 0
	HandShape_ROCK                HandShape = 1
	HandShape_PAPER               HandShape = 2
	HandShape_SCISSORS            HandShape = 3
)

// Enum value maps for HandShape.
var (
	HandShape_name = map[int32]string{
		0: "HAND_SHAPES_UNKNOWN",
		1: "ROCK",
		2: "PAPER",
		3: "SCISSORS",
	}
	HandShape_value = map[string]int32{
		"HAND_SHAPES_UNKNOWN": 0,
		"ROCK":                1,
		"PAPER":               2,
		"SCISSORS":            3,
	}
)

func (x HandShape) Enum() *HandShape {
	p := new(HandShape)
	*p = x
	return p
}

func (x HandShape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandShape) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rock_paper_scissors_proto_enumTypes[0].Descriptor()
}

func (HandShape) Type() protoreflect.EnumType {
	return &file_proto_rock_paper_scissors_proto_enumTypes[0]
}

func (x HandShape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandShape.Descriptor instead.
func (HandShape) EnumDescriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_RESULT_UNKNOWN Result = 0
	Result_WIN            Result = 1
	Result_LOSE           Result = 2
	Result_DRAW           Result = 3
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "WIN",
		2: "LOSE",
		3: "DRAW",
	}
	Result_value = map[string]int32{
		"RESULT_UNKNOWN": 0,
		"WIN":            1,
		"LOSE":           2,
		"DRAW":           3,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rock_paper_scissors_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_proto_rock_paper_scissors_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{1}
}

type MatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YourHandShape     HandShape `protobuf:"varint,1,opt,name=yourHandShape,proto3,enum=game.HandShape" json:"yourHandShape,omitempty"`
	OpponentHandShape HandShape `protobuf:"varint,2,opt,name=opponentHandShape,proto3,enum=game.HandShape" json:"opponentHandShape,omitempty"`
	Result            Result    `protobuf:"varint,3,opt,name=result,proto3,enum=game.Result" json:"result,omitempty"`
	CreatedAt         string    `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rock_paper_scissors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rock_paper_scissors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{0}
}

func (x *MatchResult) GetYourHandShape() HandShape {
	if x != nil {
		return x.YourHandShape
	}
	return HandShape_HAND_SHAPES_UNKNOWN
}

func (x *MatchResult) GetOpponentHandShape() HandShape {
	if x != nil {
		return x.OpponentHandShape
	}
	return HandShape_HAND_SHAPES_UNKNOWN
}

func (x *MatchResult) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNKNOWN
}

func (x *MatchResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handshape HandShape `protobuf:"varint,1,opt,name=handshape,proto3,enum=game.HandShape" json:"handshape,omitempty"`
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rock_paper_scissors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rock_paper_scissors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{1}
}

func (x *PlayRequest) GetHandshape() HandShape {
	if x != nil {
		return x.Handshape
	}
	return HandShape_HAND_SHAPES_UNKNOWN
}

type PlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchResult *MatchResult `protobuf:"bytes,1,opt,name=matchResult,proto3" json:"matchResult,omitempty"`
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rock_paper_scissors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rock_paper_scissors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{2}
}

func (x *PlayResponse) GetMatchResult() *MatchResult {
	if x != nil {
		return x.MatchResult
	}
	return nil
}

type History struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfGames int32          `protobuf:"varint,1,opt,name=numberOfGames,proto3" json:"numberOfGames,omitempty"`
	NumberOfWins  int32          `protobuf:"varint,2,opt,name=numberOfWins,proto3" json:"numberOfWins,omitempty"`
	MatchResults  []*MatchResult `protobuf:"bytes,3,rep,name=matchResults,proto3" json:"matchResults,omitempty"`
}

func (x *History) Reset() {
	*x = History{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rock_paper_scissors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rock_paper_scissors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{3}
}

func (x *History) GetNumberOfGames() int32 {
	if x != nil {
		return x.NumberOfGames
	}
	return 0
}

func (x *History) GetNumberOfWins() int32 {
	if x != nil {
		return x.NumberOfWins
	}
	return 0
}

func (x *History) GetMatchResults() []*MatchResult {
	if x != nil {
		return x.MatchResults
	}
	return nil
}

type ShowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShowRequest) Reset() {
	*x = ShowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rock_paper_scissors_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRequest) ProtoMessage() {}

func (x *ShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rock_paper_scissors_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRequest.ProtoReflect.Descriptor instead.
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{4}
}

type ShowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
}

func (x *ShowResponse) Reset() {
	*x = ShowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rock_paper_scissors_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse) ProtoMessage() {}

func (x *ShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rock_paper_scissors_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse.ProtoReflect.Descriptor instead.
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return file_proto_rock_paper_scissors_proto_rawDescGZIP(), []int{5}
}

func (x *ShowResponse) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

var File_proto_rock_paper_scissors_proto protoreflect.FileDescriptor

var file_proto_rock_paper_scissors_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x2d, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x2d, 0x73, 0x63, 0x69, 0x73, 0x73, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x35, 0x0a, 0x0d, 0x79, 0x6f, 0x75, 0x72, 0x48,
	0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52,
	0x0d, 0x79, 0x6f, 0x75, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x3d,
	0x0a, 0x11, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x11, 0x6f, 0x70, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x3c, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x48, 0x61, 0x6e, 0x64,
	0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x70, 0x65,
	0x22, 0x43, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x47, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4f, 0x66, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x4f, 0x66, 0x57, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x57, 0x69, 0x6e, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x37, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2a, 0x47, 0x0a, 0x09, 0x48, 0x61,
	0x6e, 0x64, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x48, 0x41, 0x4e, 0x44, 0x5f,
	0x53, 0x48, 0x41, 0x50, 0x45, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41,
	0x50, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x43, 0x49, 0x53, 0x53, 0x4f, 0x52,
	0x53, 0x10, 0x03, 0x2a, 0x39, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a,
	0x0e, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f,
	0x53, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x52, 0x41, 0x57, 0x10, 0x03, 0x32, 0x87,
	0x01, 0x0a, 0x18, 0x52, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x70, 0x65, 0x72, 0x53, 0x63, 0x69, 0x73,
	0x73, 0x6f, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x50,
	0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x77, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rock_paper_scissors_proto_rawDescOnce sync.Once
	file_proto_rock_paper_scissors_proto_rawDescData = file_proto_rock_paper_scissors_proto_rawDesc
)

func file_proto_rock_paper_scissors_proto_rawDescGZIP() []byte {
	file_proto_rock_paper_scissors_proto_rawDescOnce.Do(func() {
		file_proto_rock_paper_scissors_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rock_paper_scissors_proto_rawDescData)
	})
	return file_proto_rock_paper_scissors_proto_rawDescData
}

var file_proto_rock_paper_scissors_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_rock_paper_scissors_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_rock_paper_scissors_proto_goTypes = []interface{}{
	(HandShape)(0),       // 0: game.HandShape
	(Result)(0),          // 1: game.Result
	(*MatchResult)(nil),  // 2: game.MatchResult
	(*PlayRequest)(nil),  // 3: game.PlayRequest
	(*PlayResponse)(nil), // 4: game.PlayResponse
	(*History)(nil),      // 5: game.History
	(*ShowRequest)(nil),  // 6: game.ShowRequest
	(*ShowResponse)(nil), // 7: game.ShowResponse
}
var file_proto_rock_paper_scissors_proto_depIdxs = []int32{
	0, // 0: game.MatchResult.yourHandShape:type_name -> game.HandShape
	0, // 1: game.MatchResult.opponentHandShape:type_name -> game.HandShape
	1, // 2: game.MatchResult.result:type_name -> game.Result
	0, // 3: game.PlayRequest.handshape:type_name -> game.HandShape
	2, // 4: game.PlayResponse.matchResult:type_name -> game.MatchResult
	2, // 5: game.History.matchResults:type_name -> game.MatchResult
	5, // 6: game.ShowResponse.history:type_name -> game.History
	3, // 7: game.RockPaperScissorsService.PlayGame:input_type -> game.PlayRequest
	6, // 8: game.RockPaperScissorsService.ShowHistory:input_type -> game.ShowRequest
	4, // 9: game.RockPaperScissorsService.PlayGame:output_type -> game.PlayResponse
	7, // 10: game.RockPaperScissorsService.ShowHistory:output_type -> game.ShowResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_rock_paper_scissors_proto_init() }
func file_proto_rock_paper_scissors_proto_init() {
	if File_proto_rock_paper_scissors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rock_paper_scissors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rock_paper_scissors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rock_paper_scissors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rock_paper_scissors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*History); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rock_paper_scissors_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rock_paper_scissors_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rock_paper_scissors_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rock_paper_scissors_proto_goTypes,
		DependencyIndexes: file_proto_rock_paper_scissors_proto_depIdxs,
		EnumInfos:         file_proto_rock_paper_scissors_proto_enumTypes,
		MessageInfos:      file_proto_rock_paper_scissors_proto_msgTypes,
	}.Build()
	File_proto_rock_paper_scissors_proto = out.File
	file_proto_rock_paper_scissors_proto_rawDesc = nil
	file_proto_rock_paper_scissors_proto_goTypes = nil
	file_proto_rock_paper_scissors_proto_depIdxs = nil
}
